
version: "3.0"

services:
  socketio-client-tool:
    build: .
    image: socketio-client-tool-dev
    container_name: socketio-client-tool-dev
    environment:
      - "ROUTE_PREFIX=socket"
    ports:
      - "8081:80"
